SV = 	flopr.sv \
	floprc.sv \
	flopenr.sv \
	flopenrc.sv \
	flopens.sv \
	arrs.sv \
	adder.sv \
	mux2.sv \
	mux3.sv \
	mux4.sv \
	mux5.sv \
	mux8.sv \
	counter.sv

LIB_NAME = prims_lib
VLOG_OPTS = -quiet

include ../make.inc
