SV = 	shifter.sv \
	magcompare2c.sv \
	magcompare2b.sv \
	magcompare32.sv \
	alu.sv \
	hazard.sv \
	signext.sv \
	regfile.sv \
	datapath.sv 

LIB_NAME = datapath_lib
VLOG_OPTS = -quiet

include ../../make.inc
